# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- next

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run eslint
  displayName: 'ESLint'

- script: npm run typecheck
  displayName: 'Typecheck'

- script: npm run build
  displayName: 'Build lib'

- script: npm run build-storybook
  displayName: 'Build storybook'

- script: npm test
  displayName: 'Test'
  env: { 'CI': 'true' }

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true
